spring.datasource.url=jdbc:mysql://db:3306/rapidito?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=rapidito
spring.datasource.password=rapidito123
spring.jpa.hibernate.ddl-auto=update
app.api.base-url=http://localhost:8080/api
