spring.application.name=Rapidito

# ==========================
# Configuración de Conexión MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/rapidito
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# Configuración JPA / Hibernate
# ==========================
# create |  | update | validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==========================
# Pool de Conexiones (HikariCP - por defecto en Spring Boot)
# ==========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# ==========================
# API base URL (RestClient)
# ==========================
app.api.base-url=http://localhost:8080/api


# ==================================================================================================================================
# ==================================================================================================================================

# ================================================
# Variables de Configuración de la Aplicación
# ================================================

# Configuración de Alquiler
config.alquiler.antiguedad-carnet-minima=2
config.alquiler.edad-minima-standar=21
config.alquiler.edad-minima-premium=25
